name: MWC Messaging Workflow 0509

on:
  repository_dispatch:
    types: [start-messaging]

jobs:
  run-messenger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install playwright gspread oauth2client requests
          playwright install --with-deps chromium

      - name: Run Python Script
        env:
          MWC_EMAIL: ${{ secrets.MWC_EMAIL }}
          MWC_PASSWORD: ${{ secrets.MWC_PASSWORD }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          CUSTOM_MSG: ${{ github.event.client_payload.custom_message }}
        run: python main.py
